language: node_js
branches:
  except:
  - gh-pages
sudo: false
before_script:
  - npm install web-component-tester
  - npm install bower
  - 'export PATH=$PWD/node_modules/.bin:$PATH'
  - bower install
env:
  global:
    - NAME=i18n-format
node_js: 4
addons:
  firefox: latest
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
script:
  - xvfb-run wct
